### ISSUE TITLE
Remaking the application

### ISSUE THREAD

**Issue by vakho10** [Jaysds1/MTA-Web-GUI-Editor#3]
Hi @Jaysds1 
I like your online editor. I would like to try and remake the editor and make it more flexible using ReactJS. 
Also, I have an idea about the GUI editing. It would be a great idea to separate the GUI and LUA scripts apart.
Like in WPF or JavaFX, we have some XML file which contains GUI information and it gets bind with the code.
This would make GUI programming easier wouldn't you agree? 😃 
But, it all requires effort 😢 Anyway, is it alright to fork this project and use your code?

**Comment by Jaysds1** [comment]
Hey @vakho10 
I am very open to forks especially using the latest JS Frameworks and it would be better to have the GUI‘s in an XML format.

**Comment by vakho10** [comment]
Alrighty then :)
